In [43]:
from links_functions import get_match_link
import ace_tools_open as tools
links = get_match_link("2026-02-01", "2026-02-28", ["Ligue 1"])
tools.display_dataframe_to_user("", links)

100%|██████████| 27/27 [06:17<00:00, 14.00s/it]

In [44]:
links

,id,teams,date,league,url
0,76b5396f,Lyon Lille,2026-02-01,Ligue 1,https://fbref.com/en/matches/76b5396f/Lyon-Lil...
1,a8ad76d2,Nice Brest,2026-02-01,Ligue 1,https://fbref.com/en/matches/a8ad76d2/Nice-Bre...
2,af901063,Toulouse Auxerre,2026-02-01,Ligue 1,https://fbref.com/en/matches/af901063/Toulouse...
3,c2fd3a64,Angers Metz,2026-02-01,Ligue 1,https://fbref.com/en/matches/c2fd3a64/Angers-M...
4,fbaa262a,Strasbourg Paris Saint Germain,2026-02-01,Ligue 1,https://fbref.com/en/matches/fbaa262a/Strasbou...
5,65afe9c0,Metz Lille,2026-02-06,Ligue 1,https://fbref.com/en/matches/65afe9c0/Metz-Lil...
6,7cf482da,Lens Rennes,2026-02-07,Ligue 1,https://fbref.com/en/matches/7cf482da/Lens-Ren...
7,d34ec094,Brest Lorient,2026-02-07,Ligue 1,https://fbref.com/en/matches/d34ec094/Brest-Lo...
8,337b6509,Nantes Lyon,2026-02-07,Ligue 1,https://fbref.com/en/matches/337b6509/Nantes-L...
9,653917b7,Nice Monaco,2026-02-08,Ligue 1,https://fbref.com/en/matches/653917b7/Nice-Mon...
10,2bc15f43,Auxerre Paris FC,2026-02-08,Ligue 1,https://fbref.com/en/matches/2bc15f43/Auxerre-...
11,6f487335,Le Havre Strasbourg,2026-02-08,Ligue 1,https://fbref.com/en/matches/6f487335/Le-Havre...
12,a01e1b1c,Angers Toulouse,2026-02-08,Ligue 1,https://fbref.com/en/matches/a01e1b1c/Angers-T...
13,468775dd,Paris Saint Germain Marseille,2026-02-08,Ligue 1,https://fbref.com/en/matches/468775dd/Paris-Sa...
14,9ff84087,Rennes Paris Saint Germain,2026-02-13,Ligue 1,https://fbref.com/en/matches/9ff84087/Rennes-P...
15,c74bddc1,Monaco Nantes,2026-02-13,Ligue 1,https://fbref.com/en/matches/c74bddc1/Monaco-N...
16,5ccecb4a,Marseille Strasbourg,2026-02-14,Ligue 1,https://fbref.com/en/matches/5ccecb4a/Marseill...
17,aae28368,Lille Brest,2026-02-14,Ligue 1,https://fbref.com/en/matches/aae28368/Lille-Br...
18,38da6e69,Paris FC Lens,2026-02-14,Ligue 1,https://fbref.com/en/matches/38da6e69/Paris-FC...
19,b0f2054b,Le Havre Toulouse,2026-02-15,Ligue 1,https://fbref.com/en/matches/b0f2054b/Le-Havre...
20,57b37863,Lorient Angers,2026-02-15,Ligue 1,https://fbref.com/en/matches/57b37863/Lorient-...
21,66636882,Metz Auxerre,2026-02-15,Ligue 1,https://fbref.com/en/matches/66636882/Metz-Aux...
22,7df88dc4,Lyon Nice,2026-02-15,Ligue 1,https://fbref.com/en/matches/7df88dc4/Lyon-Nic...
23,08084e64,Brest Marseille,2026-02-20,Ligue 1,https://fbref.com/en/matches/08084e64/Brest-Ma...
24,355277c5,Lens Monaco,2026-02-21,Ligue 1,https://fbref.com/en/matches/355277c5/Lens-Mon...
25,4675af40,Toulouse Paris FC,2026-02-21,Ligue 1,https://fbref.com/en/matches/4675af40/Toulouse...
26,ac4da1f1,Paris Saint Germain Metz,2026-02-21,Ligue 1,https://fbref.com/en/matches/ac4da1f1/Paris-Sa...
27,ada27536,Auxerre Rennes,2026-02-22,Ligue 1,https://fbref.com/en/matches/ada27536/Auxerre-...
28,2b2f68a6,Nantes Le Havre,2026-02-22,Ligue 1,https://fbref.com/en/matches/2b2f68a6/Nantes-L...
29,5608e801,Nice Lorient,2026-02-22,Ligue 1,https://fbref.com/en/matches/5608e801/Nice-Lor...
30,d09c51d0,Angers Lille,2026-02-22,Ligue 1,https://fbref.com/en/matches/d09c51d0/Angers-L...
31,1c22b8d6,Strasbourg Lyon,2026-02-22,Ligue 1,https://fbref.com/en/matches/1c22b8d6/Strasbou...
32,aeb4b406,Strasbourg Lens,2026-02-27,Ligue 1,https://fbref.com/en/matches/aeb4b406/Strasbou...
33,e7e6586e,Rennes Toulouse,2026-02-28,Ligue 1,https://fbref.com/en/matches/e7e6586e/Rennes-T...
34,a594ae3b,Monaco Angers,2026-02-28,Ligue 1,https://fbref.com/en/matches/a594ae3b/Monaco-A...
35,87a753e0,Le Havre Paris Saint Germain,2026-02-28,Ligue 1,https://fbref.com/en/matches/87a753e0/Le-Havre...

In [8]:
from match_functions import get_match

In [2]:
from datetime import datetime, timedelta
from tqdm import tqdm
import undetected_chromedriver as uc
from bs4 import BeautifulSoup
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.common.exceptions import TimeoutException
import pandas as pd
from urllib.parse import urlparse

In [45]:
all_stats = pd.DataFrame()

In [46]:
links_match = list(links["url"])
driver = uc.Chrome(version_main=145)

In [52]:
lm = links_match[1]

In [53]:
driver.get(lm)

In [54]:
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")

In [55]:
stat = get_match(soup)

In [56]:
pd.concat([all_stats, stat])

,leagues,journey,season,date,hours,referee,stadium,team_name_home,team_name_away,score_home,...,red_card_dom,red_card_ext,Manager_home,Manager_away,Captain_home,Captain_away,Compo_home,Compo_away,Teams_home,Teams_away
0,Ligue 1,Matchweek 20,2025/2026,01/02/2026,17:15,Stéphanie Frappart,Allianz Riviera,Nice,Brest,2,...,0,0,Claude Puel,Eric Roy,Dante,Brendan Chardonnet,4-2-3-1,4-2-3-1,"[Maxime Dupé, Ali Abdi, Dante, Morgan Sanson, ...","[Grégoire Coudert, Brendan Chardonnet, Hugo Ma..."

In [57]:
all_stats = pd.DataFrame()
links_match = list(links["url"])
driver = uc.Chrome(version_main=145)
time.sleep(10)
for lm in tqdm(links_match):
    driver.get(lm)
    time.sleep(10)
    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")
    stat = get_match(soup)
    all_stats = pd.concat([all_stats, stat])
driver.quit()

100%|██████████| 36/36 [06:34<00:00, 10.95s/it]

In [60]:
all_stats = all_stats.reset_index(drop=True)

In [61]:
import ace_tools_open as tools
tools.display_dataframe_to_user("", all_stats)

In [3]:
driver = uc.Chrome(version_main=145)

In [4]:
lm = "https://fbref.com/en/matches/76b5396f/Lyon-Lille-February-1-2026-Ligue-1"

In [5]:
driver.get(lm)

In [6]:
html = driver.page_source
soup = BeautifulSoup(html, "html.parser")

In [10]:
stat = get_match(soup)

In [11]:
import ace_tools_open as tools
tools.display_dataframe_to_user("", stat)

In [12]:
soup.find_all("div", class_="score_xg")

[]

In [ ]:
def get_xg(soup):
    code = soup.find_all("div", class_="score_xg")
    try:
        xg_home = float(code[0].text)
        xg_away = float(code[1].text)
    except (IndexError, ValueError):
        xg_home, xg_away = "NaN", "NaN" 
    return pd.DataFrame([{"xg_home": xg_home, "xg_away": xg_away}])